name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest
          platforms: linux/arm64

  deploy:
    name: Deploy to VM
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key

      - name: Deploy docker-compose and Image to VM
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KEYSCAN_OUTPUT }}" >> ~/.ssh/known_hosts
          ssh -i private_key ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} "\
          cd blog && \
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest && \
          docker compose -f docker-compose.yml up -d"

      - name: Cleanup SSH key
        run: rm -f private_key
